import java.util.List;

public class DataBis {
    public DataBis() {
    }

    private List<DepartmentInfos> departmentInfos = List.of(
        new DepartmentInfos(1, "Ain"),
        new DepartmentInfos(2, "Aisne"),
        new DepartmentInfos(3, "Allier"),
        new DepartmentInfos(4, "Alpes-de-Haute-Provence"),
        new DepartmentInfos(5, "Hautes-Alpes"),
        new DepartmentInfos(6, "Alpes-Maritimes"),
        new DepartmentInfos(7, "Ardèche"),
        new DepartmentInfos(8, "Ardennes"),
        new DepartmentInfos(9, "Ariège"),
        new DepartmentInfos(10, "Aube"),
        new DepartmentInfos(11, "Aude"),
        new DepartmentInfos(12, "Aveyron"),
        new DepartmentInfos(13, "Bouches-du-Rhône"),
        new DepartmentInfos(14, "Calvados"),
        new DepartmentInfos(15, "Cantal"),
        new DepartmentInfos(16, "Charente"),
        new DepartmentInfos(17, "Charente-Maritime"),
        new DepartmentInfos(18, "Cher"),
        new DepartmentInfos(19, "Corrèze"),
        new DepartmentInfos(20, "Corse"),
        new DepartmentInfos(21, "Côte-d'Or"),
        new DepartmentInfos(22, "Côtes-d'Armor"),
        new DepartmentInfos(23, "Creuse"),
        new DepartmentInfos(24, "Dordogne"),
        new DepartmentInfos(25, "Doubs"),
        new DepartmentInfos(26, "Drôme"),
        new DepartmentInfos(27, "Eure"),
        new DepartmentInfos(28, "Eure-et-Loir"),
        new DepartmentInfos(29, "Finistère"),
        new DepartmentInfos(30, "Gard"),
        new DepartmentInfos(31, "Haute-Garonne"),
        new DepartmentInfos(32, "Gers"),
        new DepartmentInfos(33, "Gironde"),
        new DepartmentInfos(34, "Hérault"),
        new DepartmentInfos(35, "Ille-et-Vilaine"),
        new DepartmentInfos(36, "Indre"),
        new DepartmentInfos(37, "Indre-et-Loire"),
        new DepartmentInfos(38, "Isère"),
        new DepartmentInfos(39, "Jura"),
        new DepartmentInfos(40, "Landes"),
        new DepartmentInfos(41, "Loir-et-Cher"),
        new DepartmentInfos(42, "Loire"),
        new DepartmentInfos(43, "Haute-Loire"),
        new DepartmentInfos(44, "Loire-Atlantique"),
        new DepartmentInfos(45, "Loiret"),
        new DepartmentInfos(46, "Lot"),
        new DepartmentInfos(47, "Lot-et-Garonne"),
        new DepartmentInfos(48, "Lozère"),
        new DepartmentInfos(49, "Maine-et-Loire"),
        new DepartmentInfos(50, "Manche"),
        new DepartmentInfos(51, "Marne"),
        new DepartmentInfos(52, "Haute-Marne"),
        new DepartmentInfos(53, "Mayenne"),
        new DepartmentInfos(54, "Meurthe-et-Moselle"),
        new DepartmentInfos(55, "Meuse"),
        new DepartmentInfos(56, "Morbihan"),
        new DepartmentInfos(57, "Moselle"),
        new DepartmentInfos(58, "Nièvre"),
        new DepartmentInfos(59, "Nord"),
        new DepartmentInfos(60, "Oise"),
        new DepartmentInfos(61, "Orne"),
        new DepartmentInfos(62, "Pas-de-Calais"),
        new DepartmentInfos(63, "Puy-de-Dôme"),
        new DepartmentInfos(64, "Pyrénées-Atlantiques"),
        new DepartmentInfos(65, "Hautes-Pyrénées"),
        new DepartmentInfos(66, "Pyrénées-Orientales"),
        new DepartmentInfos(67, "Bas-Rhin"),
        new DepartmentInfos(68, "Haut-Rhin"),
        new DepartmentInfos(69, "Rhône"),
        new DepartmentInfos(70, "Haute-Saône"),
        new DepartmentInfos(71, "Saône-et-Loire"),
        new DepartmentInfos(72, "Sarthe"),
        new DepartmentInfos(73, "Savoie"),
        new DepartmentInfos(74, "Haute-Savoie"),
        new DepartmentInfos(75, "Paris"),
        new DepartmentInfos(76, "Seine-Maritime"),
        new DepartmentInfos(77, "Seine-et-Marne"),
        new DepartmentInfos(78, "Yvelines"),
        new DepartmentInfos(79, "Deux-Sèvres"),
        new DepartmentInfos(80, "Somme"),
        new DepartmentInfos(81, "Tarn"),
        new DepartmentInfos(82, "Tarn-et-Garonne"),
        new DepartmentInfos(83, "Var"),
        new DepartmentInfos(84, "Vaucluse"),
        new DepartmentInfos(85, "Vendée"),
        new DepartmentInfos(86, "Vienne"),
        new DepartmentInfos(87, "Haute-Vienne"),
        new DepartmentInfos(88, "Vosges"),
        new DepartmentInfos(89, "Yonne"),
        new DepartmentInfos(90, "Territoire de Belfort"),
        new DepartmentInfos(91, "Essonne"),
        new DepartmentInfos(92, "Hauts-de-Seine"),
        new DepartmentInfos(93, "Seine-Saint-Denis"),
        new DepartmentInfos(94, "Val-de-Marne"),
        new DepartmentInfos(95, "Val-d'Oise"),
        new DepartmentInfos(971, "Guadeloupe"),
        new DepartmentInfos(972, "Martinique"),
        new DepartmentInfos(973, "Guyane"),
        new DepartmentInfos(974, "La Réunion"),
        new DepartmentInfos(976, "Mayotte"),
        new DepartmentInfos(977, "Saint-Barthélemy"),
        new DepartmentInfos(978, "Saint-Martin"),
        new DepartmentInfos(984, "Terres australes et antarctiques françaises"),
        new DepartmentInfos(986, "Wallis-et-Futuna"),
        new DepartmentInfos(987, "Polynésie française"),
        new DepartmentInfos(988, "Nouvelle-Calédonie")
    );

    public List<DepartmentInfos> getDepartmentInfos() {
        return departmentInfos;
    }

    public void setDepartmentInfos(List<DepartmentInfos> departmentInfos) {
        this.departmentInfos = departmentInfos;
    }
}
